sudo: required
dist: trusty

language: node_js
node_js:
  - '4.5'

addons:
  sonarqube:
    token:
      secure: pzmi5w3IYo/jbQiE4Lo2Pcg3aMOJF7n9up5Xj6cUAAPX4HTt6cZXjjIZ2HvyIHT9fXe8TWynGAezoSw6QybmLqdUU8RTAvJfGA/f+Dnns2brgccTG9ZAdXRWXsDKUPFwWxIcsIH3f/FG4BZjutUUvQnULgLHlaQXNw6L8ZSYHAGZShNLAw5r52LEiwBYeCDZ7n6rfzuLY47YOHlhocl+4eq2JoxL2ZoWS95SWNZt7NtDJ6wjl2zkB8aRTn5ZDziH3piJj6hUp5FOw2CxBxGnNv0GNM6kLOUTEo/Qte1b6A8gObgvpoxroorioNKmvlpsaaV+jGycXcRVC1OFTaRh/ftk7Z2tM7YORkvk5rDaoOfSLiDOXZ/lI6amZZJyT4zgZEZTgK3lUpJ0ZLoS90KSZUaooambQFqVDre3vLeeU9xp4VHjTv/siH/zeyGTM7WaFd3imkakjXIuUinDqGjZyXjO78zkfUlRFkmxbwqjkv29nRG43BFYknKS5Ar5KtGCWK8KAb13YEff+2rqx38tujyfene/0ASjg46Q8a4ckALw7GdewcdkaZs154OP0jeGN0/i8VWSg58Yfx5h384J/4iwYx/Qu7kizeaCNS38rt2pMCoRy+X+ivenq/Cu9T760/nA6P/qcZ+plSdyPtxFEwS9BRqTFokdKpvxYjSfmkw=

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update -q
  - sudo apt-get install -q google-chrome-stable

before_script:
  - npm install

script:
  - npm run test-single-run
  - (npm start > /dev/null &) && (npm run protractor)
  - sonar-scanner
