sudo: required
dist: trusty

language: node_js
node_js:
  - '4.5'

addons:
  sonarqube:
    token:
      secure: pLO5ikPf3Yd9J5ZF3UfdQoWqg9r/I1zzEpMxUUPIvcWiM9KuglY/08Mj5qG5KWoeJQnxBOiNhvVDt+HIrwv8li9ugpDwqCQ6rUQCb+u+uxKCIHaiT7pLSPHV2meA/XSt/aXN+yxaP2xz7YOD51abX5f3qhDTfzUcBjChpTy6tZrxOkZ8DfHxB6NqPz4UEZBd+uzk+r9Z/oP1HVhDwpSRPNbe9jOgav3aCkusbeZOZezhQTi8TXO+4Maio3NYFtOfwgE7g/X5LBlnHP7bIampknZvffUuOOoqK+TlyErzcFyKFjL9QEIgOLDwvHHfQgMy9U8Vjie+UUws7yh9GOyMB+p0ZB04t1SSBRChrfVgyW9Pg56AdyMwCY5wcpxaRmHn3fLNU7Pb0gJPyQNt6JVf99FyMzrIZPby3Le9JyVbL/6lS4H29I37Lwjyp2IjiaMrXaF/6Qsg/vaPMdm0GfXJ7cGSpXLVQZCATUC6FdreAoF41gmMvicG0GaFakHlhsSfCSoZeOyeRQGELD0+mhf4fxOCHIRivXNZFtNFgNmx5021Gny+n6LagdtzQ4R2pJbJPFtzz0tWgsNaUi2LR0CirfYHouP2y/zuf+A4nIcspwMipYZDCX4zrWYFsjJ+trK4IO168ozIOb/eEAWvn5ABSbkqTsQIGHq0VV+5mygty9A=
    branches:
      - master
      - /.*/

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update -q
  - sudo apt-get install -q google-chrome-stable

before_script:
  - npm install

script:
  - npm run test-single-run
  - (npm start > /dev/null &) && (npm run protractor)
  - sonar-scanner

deploy:
  provider: heroku
  app: rocketvoip-frontend
  api_key:
    secure: KsOWCuLFjFax0n6NI6MBu9QooMdiHDLeCuuCuuwVYtcsM0aH80bCEWlZ5MoitNbeQ3l4G9g2WXu1ftA54pYgILHd8FoJ+uRa/jEtHXMa1FdZkNQSbRzaNgfizfxnAiNcvBpm5rGrlRs2yoVKpy/V7M6jeO5sPjhTCj+RMHa6iHhlvBzb3iGMTWdK9Xf0j408AvJrSeY5JECXkvBS7Ak/e0s6syMokRIUah5/4d/P1a3ym2/gcI9ulsHNTc7uP7fiFApDUBcrBBJLkwz8gf7iB/1H9+7iUJxvACc4oTx6HNbUh64dzayPmTY1Gb7LALrlElOEQSTTsyein5OpK43Zpi1DsB9JDYdJr/ycdck5s3N7HjaHqHViEAzNdBigeD1GPFDx6MX0KqDQAWTCdcSN9lSuuGQC3SiRgYdFvWYnNvD/LxlrHduTB0x4XXicAXfaSj6JJOYycBxD5Ic5HPw1YRnzJvwzXo0gLLSToHQacm42zqVKpl9zbuFb5MWEZi9q7DvmytWWxcnXYc+dO7xIUYtqWYe4VRcJTrdKFHPyLPHKzZB8VFWGA+5n5CCjV08UpjDvcMGDFR97PbTTT+bTIb9gSpXtXjRxchLju0FC2B6xl1fFWRTKca4sBNs2cC+wqvjs6NAn5ixkG6Ij4UG+9YhYw5Jj+keB1p7mTFlwGao=

COVERALLS_REPO_TOKEN:
  secure: d2/mVFLdcmfhNJiCwwbEPAAdr0jdYP64a1+q/CjXWrO0Ws2tSDIN1HCtve1KIHA2sy3cqPB1B2yBJJCKL3PF+wb8IXrkDstzrQgmpSf1DIOpZi8Aer5wnNc35aIIKye3mtCBhexpROfZCnYQKcpXziVS2iMDXw0y4Qd0SjMZ6wTwJGM8Fou1W3zd8WgoiMQARcurHvZl5gMRI502WN6lYvneifqTmhibEENNbyvW1T+++Vr/fIk3sRh28pATU61i9YmT3kIlAzr3CEVKEPegAki90eP8gaMt+ycIWOjCocTwGpierAYBohxLZkX7Sb06CRbSNpmuHzBUpNzFNWIaEwjhREWquRfjIYNQ6ALoIF4+jzzTLPYvazDfpkQoF0GqAy8BaQnBXsEO4Gi4yn9Hdwb2JDz8JEKvUKSc3VRrR+7jJwZ2PNEtKKzRZDYq9KyALdWWZHr8HsgUFmRVAJ3r8xbjuMXs07810xzzFi0B0LFt4CR8tPuJSbMQHasJyzBHA3uZ8C7IlTZ9owE9ibvaT/ha5crYG/2xUz0GVVNHPA2QL6MD5pR+4l/ACi1LdHOhtObKgDmwVprBaXxU15VGpRW89zvCXR8xrwkyWl3wCIZRcsZYPcD+vfQlY44M2WHhonn5VxeJ55SgjJkINuRgxR5x9nSe+buH1oYzog3ymKM=
#SONAR_TOKEN:
#  secure: pLO5ikPf3Yd9J5ZF3UfdQoWqg9r/I1zzEpMxUUPIvcWiM9KuglY/08Mj5qG5KWoeJQnxBOiNhvVDt+HIrwv8li9ugpDwqCQ6rUQCb+u+uxKCIHaiT7pLSPHV2meA/XSt/aXN+yxaP2xz7YOD51abX5f3qhDTfzUcBjChpTy6tZrxOkZ8DfHxB6NqPz4UEZBd+uzk+r9Z/oP1HVhDwpSRPNbe9jOgav3aCkusbeZOZezhQTi8TXO+4Maio3NYFtOfwgE7g/X5LBlnHP7bIampknZvffUuOOoqK+TlyErzcFyKFjL9QEIgOLDwvHHfQgMy9U8Vjie+UUws7yh9GOyMB+p0ZB04t1SSBRChrfVgyW9Pg56AdyMwCY5wcpxaRmHn3fLNU7Pb0gJPyQNt6JVf99FyMzrIZPby3Le9JyVbL/6lS4H29I37Lwjyp2IjiaMrXaF/6Qsg/vaPMdm0GfXJ7cGSpXLVQZCATUC6FdreAoF41gmMvicG0GaFakHlhsSfCSoZeOyeRQGELD0+mhf4fxOCHIRivXNZFtNFgNmx5021Gny+n6LagdtzQ4R2pJbJPFtzz0tWgsNaUi2LR0CirfYHouP2y/zuf+A4nIcspwMipYZDCX4zrWYFsjJ+trK4IO168ozIOb/eEAWvn5ABSbkqTsQIGHq0VV+5mygty9A=