sudo: required
dist: trusty

language: node_js
node_js:
  - '4.5'

addons:
  sonarqube:
    token:
      secure: "Y/tTtZ88zNy6BUeff567MaYq10S4B0cm9Fl+xUD78AIRnBTLhhTkP1qW3baI2GnazX4uzOPqMr/cVNOmh+UoZ4ddFrIxFrit5QQ8Ft2yEAoHdiAEtDWjzMFRM6i4KVUIKCQ+gfh17+FHkluEC1jCNdyGE/L2aIsnx7vDJ5TqCVRnWHAmcPaYEr4NkcUPldgKLfbrQglR339oHZO+mG/dMyV61Tv0i6/MZXzBZc1D3dfDxkXFEG8wO2Fz99fj5+lubZmefxNOhN1tu7iCtZ/ppTaJj3F7sOl91V7MW25oPA+a0A2Axg+wxZ/93t4+D3K/tvJkNbBMb6XwmsGPvMA4BKbylK8rvJVEbOIpaSX4vTQV2hHJvCM3MLjw8+O4NgOkX8UmPD82iIbx8NXiPZKerg4zgbHWJox21Yz50qHEY9jZ8dJkBo3zcKAjKvvbqfCIn04ar5L1qNnrEGxO/NOSb2PfqXATE5/DTVD/sX6tuSCQKEyWmxamx8Bk/Zd0eRn9cVCNaD3jY3m6DiQ6zS0VJpt7OTeOOrFk3hd2CPvV9Ntiuoq+dQH0gROgabZ88wC/oiMTxMoXie7PpSqCt0iNHKLYykJHmMvLtGuvsukfsJ2+m6ww4SMQRFzvo6dli6BTPf97/BSCbJV7Q+jgZQ8/rc8pEmyTqvkRVG84eat6eao="

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update -q
  - sudo apt-get install -q google-chrome-stable

before_script:
  - npm install

script:
  - npm run test-single-run
  - (npm start > /dev/null &) && (npm run protractor)
  - sonar-scanner -X
