sudo: required
dist: trusty

language: node_js
node_js:
  - '4.5'

addons:
  sonarqube:
    token:
      secure: HGMPRZJw4qUB8sgod/T/sotuus8bA+ZgoInLhKYan76gtrEmXSkoIv5HXN0grrKP+NK1YiiRlLnojUoBLH6JN28NZ3FewrYPWnPh2co4zKzV+C2kpurx+Wk5h/nZzSBNM+y2CsNpZVNjZgT+AxZUjE8njZnguliZEKSnbxbvs/CA5TM+wY0rs4xVtMbZ2Kbb84R8pquJKrzuGpijfjDzcsFzL2dyAbPksfTUzfc9E2piLQGUMtb2nfFvSkNg7bW6440XTivEDWgIIMrXm/loPHtQITPOxIGinaESqyNq1qhncjGZCnspWq3dBRDIb/6tKor1lwavapK2LNSRFiaNCYJeViz+/KqjopTwUI3ybYxSt/vPj9gAeh9gws85YH5D1W95NwatQTrYQNDGHxJ/WCo3wlAAkzina+GuwRKPGTBiovFUf0nEx2u5PIjetCccR9rPNlQZwE/zQKI+GnOma/vZgtOO8Hz/iWAhHEDK9Ucq3G1F7j+BUmxx8jGbS0DK9yLgMYS7sBqSgVkDEQp0W/qcYjQNYVBOQQoMzoCQ1qkpWRNeM2aHAgzPtLx3bvUJBK7rTPpIciRwmHciCML/4CWC3/SthDbbgRmfWlp/LGr/Ij9VtQwn88WtA7zK3BC+M0N3g17lwINEuy/k7KMT+g+w+oawFcgXdbixZMnhilk=

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update -q
  - sudo apt-get install -q google-chrome-stable

before_script:
  - npm install

script:
  - npm run test-single-run
  - (npm start > /dev/null &) && (npm run protractor)
  - sonar-scanner -X
